[project]
name = "metabolic-risk-predictor"
version = "0.1.0"
requires-python = ">=3.9"

dependencies = [
    "streamlit",
    "pandas",
    "numpy",
    "scikit-learn",
    "xgboost",
    "matplotlib",
    "seaborn"
]